# Generated by Django 5.2.4 on 2025-07-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("enrollment_number", models.CharField(max_length=20, unique=True)),
                ("department", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("contact_number", models.CharField(blank=True, max_length=15)),
            ],
        ),
    ]
